# Generated by Django 6.0.6 on 2026-07-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_accessrequest_manager_accessrequest_manager_comment_and_more'),
        ('assets', '0002_alter_asset_options_alter_assetassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expirée'), ('REVOKED', 'Révoquée')], default='ACTIVE', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('access_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='access.accessrequest')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='assets.asset')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilitation',
                'verbose_name_plural': 'Habilitations',
                'ordering': ['-granted_at'],
            },
        ),
    ]
