# Generated by Django 6.0.6 on 2026-07-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
    ]
