# Generated by Django 6.0.6 on 2026-07-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('COMPLIANT', 'Conforme'), ('NON_COMPLIANT', 'Non conforme'), ('WARNING', 'Avertissement')], max_length=20)),
                ('recommendation', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrôle de conformité',
                'verbose_name_plural': 'Contrôles de conformité',
                'ordering': ['-checked_at'],
            },
        ),
    ]
