# Generated by Django 6.0.6 on 2026-07-11 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('assets', '0002_alter_asset_options_alter_assetassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='manager_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='manager_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rssi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rssi_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rssi_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rssi_validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('MANAGER_APPROVED', 'Validée par le responsable'), ('MANAGER_REJECTED', 'Refusée par le responsable'), ('RSSI_APPROVED', 'Validée par le RSSI'), ('RSSI_REJECTED', 'Refusée par le RSSI'), ('COMPLETED', 'Terminée'), ('REVOKED', 'Révoquée')], default='PENDING', max_length=30),
        ),
    ]
