# Generated by Django 6.0.6 on 2026-07-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accessrequest_manager_accessrequest_manager_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={},
        ),
    ]
