# Generated by Django 6.0.6 on 2026-07-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_accessrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_manager', 'Peut valider une demande en tant que Responsable'), ('approve_rssi', 'Peut valider une demande en tant que RSSI'), ('revoke_access', 'Peut révoquer un accès'), ('approve_accessrequest', 'Can approve access request'), ('reject_accessrequest', 'Can reject access request'), ('revoke_accessrequest', 'Can revoke access request')], 'verbose_name': "Demande d'accès", 'verbose_name_plural': "Demandes d'accès"},
        ),
    ]
